# Generated by Django 5.2.5 on 2025-10-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли роль стандартной (создается автоматически)', verbose_name='Стандартная роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Разрешения, назначенные этой роли', related_name='roles', to='auth.permission', verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
                'permissions': [('can_manage_team', 'Может управлять командой'), ('can_invite_members', 'Может приглашать участников'), ('can_remove_members', 'Может удалять участников'), ('can_assign_roles', 'Может назначать роли'), ('can_change_team_status', 'Может изменять статус команды'), ('can_create_project', 'Может создавать проекты'), ('can_manage_project', 'Может управлять проектами'), ('can_delete_project', 'Может удалять проекты'), ('can_assign_chapters', 'Может назначать главы'), ('can_edit_content', 'Может редактировать контент'), ('can_review_content', 'Может рецензировать контент'), ('can_publish_content', 'Может публиковать контент')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('disbanded', 'Распущена')], default='active', help_text='Текущий статус команды', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли участник в команде')),
                ('roles', models.ManyToManyField(to='teams.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='teams.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Создана'), ('deactivated', 'Приостановлена'), ('reactivated', 'Возобновлена'), ('disbanded', 'Распущена')], max_length=20)),
                ('old_status', models.CharField(blank=True, choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('disbanded', 'Распущена')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('disbanded', 'Распущена')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Причина изменения статуса')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_status_changes', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='teams.team')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли роль для пользователя', verbose_name='Активна')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначена')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_global_roles', to=settings.AUTH_USER_MODEL, verbose_name='Назначена пользователем')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_users', to='teams.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Глобальная роль пользователя',
                'verbose_name_plural': 'Глобальные роли пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'is_active'], name='teams_teamm_team_id_e0780a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('user', 'team')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='teams_team_status_d66a03_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['creator', 'status'], name='teams_team_creator_acf07f_idx'),
        ),
        migrations.AddIndex(
            model_name='teamstatushistory',
            index=models.Index(fields=['team', '-timestamp'], name='teams_teams_team_id_f6e4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='teamstatushistory',
            index=models.Index(fields=['changed_by', '-timestamp'], name='teams_teams_changed_f03175_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='teams_userr_user_id_1c05b5_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='teams_userr_role_id_6a5544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
