# Generated by Django 5.2.5 on 2025-10-13 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'is_active'], name='teams_teamm_user_id_4436db_idx'),
        ),
    ]
