# Generated by Django 5.2.5 on 2025-11-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammembership_teams_teamm_user_id_4436db_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Активен ли участник в команде'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
