# Generated by Django 5.2.5 on 2025-11-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teammembership_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamStatusHistory',
        ),
    ]
