# Generated by Django 5.2.5 on 2025-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Информация о себе (до 500 символов)', max_length=500),
        ),
    ]
