# Generated by Django 5.2.5 on 2025-11-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_connected_at',
            field=models.DateTimeField(blank=True, help_text='Дата подключения Telegram аккаунта (заглушка)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Telegram ID пользователя (заглушка)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, help_text='Telegram username (заглушка)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='users_telegram_id_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_username'], name='users_telegram_username_idx'),
        ),
    ]
