# Generated by Django 5.2.5 on 2025-11-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_telegram_connected_at_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
