# Generated by Django 5.2.5 on 2025-10-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('manga', 'Манга'), ('manhwa', 'Манхва'), ('manhua', 'Маньхуа')], default='manga', max_length=10, verbose_name='Тип проекта')),
                ('age_rating', models.CharField(choices=[('general', 'Обычная'), ('adult', '18+')], default='general', max_length=10, verbose_name='Возрастной рейтинг')),
                ('content_folder', models.CharField(blank=True, max_length=100, verbose_name='Папка контента')),
                ('status', models.CharField(choices=[('translating', 'Переводим'), ('dropped', 'Заброшен'), ('completed', 'Переведён'), ('frozen', 'Заморожен')], default='translating', max_length=20, verbose_name='Статус проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('raw', 'RAW'), ('translating', 'Перевод'), ('cleaning', 'Клининг'), ('typesetting', 'Тайпинг'), ('editing', 'Редактура'), ('done', 'Готово')], default='raw', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
