# Generated by Django 5.2.5 on 2025-11-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file_path',
            field=models.CharField(blank=True, help_text='Относительный путь к файлу (например: raw/page_001.png)', max_length=500, null=True, verbose_name='Путь к файлу'),
        ),
    ]
