# Generated by Django 5.2.5 on 2025-10-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glossary', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterUniqueTogether(
            name='glossaryterm',
            unique_together={('term', 'project')},
        ),
    ]
