# Generated by Django 5.2.7 on 2025-10-14 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для общих терминов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='projects.project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='GlossaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('content_type', models.CharField(choices=[('manga', 'Манга (японский)'), ('manhwa', 'Манхва (корейский)'), ('manhua', 'Маньхуа (китайский)'), ('general', 'Общие термины')], max_length=10, verbose_name='Тип контента')),
                ('scope', models.CharField(choices=[('global', 'Глобальный (для всех)'), ('user', 'Пользовательский'), ('project', 'Проектный')], default='global', max_length=10, verbose_name='Область видимости')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Категория глоссария',
                'verbose_name_plural': 'Категории глоссария',
                'ordering': ['content_type', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='glossaryterm',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='glossary.glossarycategory', verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='glossaryterm',
            unique_together={('term', 'category')},
        ),
    ]
