# Generated by Django 5.2.7 on 2025-10-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_glossaryterm_is_active_alter_glossaryterm_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossarycategory',
            options={'ordering': ['content_type', 'name'], 'verbose_name': 'Категория статей', 'verbose_name_plural': 'Категории статей'},
        ),
        migrations.AlterModelOptions(
            name='glossaryterm',
            options={'ordering': ['term'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='definition',
            field=models.TextField(verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='term',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
