# Generated by Django 5.2.5 on 2025-10-13 15:27

import django.db.models.deletion
import utils.file_system
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to=utils.file_system.project_image_upload_path, verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('file_size', models.IntegerField(verbose_name='Размер файла (байт)')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('document_type', models.CharField(choices=[('glossary', 'Глоссарий'), ('notes', 'Заметки'), ('reference', 'Справочные материалы'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=utils.file_system.project_document_upload_path, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('file_size', models.IntegerField(verbose_name='Размер файла (байт)')),
            ],
            options={
                'verbose_name': 'Документ проекта',
                'verbose_name_plural': 'Документы проектов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('draft_content', models.TextField(blank=True, verbose_name='Черновик контента')),
                ('last_autosave', models.DateTimeField(blank=True, null=True, verbose_name='Последнее автосохранение')),
            ],
            options={
                'verbose_name': 'Текстовый контент',
                'verbose_name_plural': 'Текстовый контент',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_text', 'Создание текста'), ('update_text', 'Обновление текста'), ('delete_text', 'Удаление текста'), ('autosave_text', 'Автосохранение текста'), ('create_project', 'Создание проекта'), ('update_project', 'Обновление проекта'), ('delete_project', 'Удаление проекта'), ('upload_image', 'Загрузка изображения'), ('delete_image', 'Удаление изображения'), ('view_project', 'Просмотр проекта'), ('access_denied', 'Отказ в доступе')], max_length=20, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог аудита контента',
                'verbose_name_plural': 'Логи аудита контента',
                'ordering': ['-timestamp'],
            },
        ),
    ]
