# Generated by Django 5.2.5 on 2025-10-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='content_con_user_id_d296bc_idx'),
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='content_con_action_8f0ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='content_con_object__5bbc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecontent',
            index=models.Index(fields=['project', '-uploaded_at'], name='content_ima_project_a85cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecontent',
            index=models.Index(fields=['uploader', '-uploaded_at'], name='content_ima_uploade_1a3109_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', '-uploaded_at'], name='content_pro_project_a2210a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='content_pro_uploade_5b489d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['document_type', '-uploaded_at'], name='content_pro_documen_59b066_idx'),
        ),
        migrations.AddIndex(
            model_name='textcontent',
            index=models.Index(fields=['project', '-updated_at'], name='content_tex_project_5fc3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='textcontent',
            index=models.Index(fields=['author', '-updated_at'], name='content_tex_author__e029b7_idx'),
        ),
    ]
