# Generated by Django 5.2.5 on 2025-11-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_unused_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentauditlog',
            name='action',
            field=models.CharField(choices=[('create_project', 'Создание проекта'), ('update_project', 'Обновление проекта'), ('delete_project', 'Удаление проекта'), ('view_project', 'Просмотр проекта'), ('access_denied', 'Отказ в доступе')], max_length=20, verbose_name='Действие'),
        ),
    ]
