# Generated by Django 5.2.5 on 2025-11-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contentauditlog_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentAuditLog',
        ),
    ]
